package clotas

const DefaultTemplate = `#!/usr/bin/env bash
#
# This file is generated CLOTA file -  see https://github.com/davidlukac/go-clotas for details.
# Generated by {{ .GeneratedBy }} at {{ .GeneratedTimestamp }}.
#
# Add your script here:

echo "Running CLOTA script {{ .Name }}"
`
